name: Test composite action

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  local-actions:
    runs-on: ubuntu-latest

    services:
      mysql: 
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3306:3306  # Mapea el puerto correctamente

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: ls
        uses: ./.github/actions/my-actions
        with:
          message: "yotas"
