name: Test composite action

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  local-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: ls
        uses: ./.github/actions/my-actions
        with:
          message: "yotas"


      